name: Deploy Spring Boot Backend (Gradle) with Java 23

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: "temurin" # Use 'zulu' or 'oracle' if needed
          java-version: "23"

      - name: Verify Java Version
        run: java -version

      - name: Grant Execute Permission for Gradlew
        run: chmod +x backend/gradlew

      - name: Build Backend with Gradle
        run: cd backend && ./gradlew build

      - name: Run Backend
        run: |
          cd backend
          nohup java -jar build/libs/*.jar > backend.log 2>&1 &
