name: Trigger Render Deployment for Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST "https://api.render.com/deploy/srv-xxxxxx?key=your-api-key"
