name: Deploy Vite React Frontend

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Repository Contents (Debugging)
        run: ls -R

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Remove `node_modules` and `package-lock.json` (Fix Rollup Issue)
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force

      - name: Install Dependencies & Build
        run: |
          npm install
          npm audit fix --force  # Fix vulnerabilities
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
